//
// Created by yhl on 18-12-7.
//
#ifndef MATRIX_BASE_ALGORITHM_BASE_H
#define MATRIX_BASE_ALGORITHM_BASE_H
#include "define.h"

#include <MATH/math_define.h>

MATH_NAMESPACE_BEGIN
ALGORITHM_NAMESPACE_BEGIN




ALGORITHM_NAMESPACE_END
MATH_NAMESPACE_END
#endif //MATRIX_BASE_ALGORITHM_BASE_H
