//
// Created by yhl on 18-12-7.
//
#include "define.h"
#ifndef MATRIX_BASE_ALGORITHM_BASE_H
#define MATRIX_BASE_ALGORITHM_BASE_H
ALGORITHM_NAMESPACE_BEGIN




ALGORITHM_NAMESPACE_END
#endif //MATRIX_BASE_ALGORITHM_BASE_H
